cart/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

import product.views
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>/', views.detail, name='detail'),
    # path('/register', views.register, name='register'),
    # path('create/', views.ProductCreate.as_view(), name='register'),
    path('create/', views.product_create, name='register'),
    path('modify/<int:product_id>/', views.product_modify, name='modify'),
    path('delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('search', views.search, name='search'),

]

cart/models.py
from django.db import models

from product.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

cart/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404

from cart.models import Cart, CartItem
from product.models import Product

import stripe
from django.conf import settings


@login_required(login_url='common:login')
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


@login_required(login_url='common:login')
def add_cart(request, product_id):
    """
    cart 한개씩 추가
    """
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


@login_required(login_url='common:login')
def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total)
    description = 'Best SmartPhone Shop - 주문'
    data_key = settings.STRIPE_PUBLIC_KEY
    if request.method == 'POST':
        print(request.POST)
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            customer = stripe.Customer.create(
                email=email,
                source=token
            )
            charge = stripe.Charge.create(
                amount=stripe_total,
                currency="krw",
                description=description,
                customer=customer.id
            )
        except stripe.error.CardError as e:
            return False, e
        return render(request, 'cart/pay.html', dict(stripe_total=stripe_total, cart_items=cart_items))

    return render(request, 'cart/cart.html', dict(cart_items=cart_items, total=total, counter=counter,
                                                  data_key=data_key, stripe_total=stripe_total,
                                                  description=description))


@login_required(login_url='common:login')
def cart_remove(request, product_id):
    """
    cart 한개씩 삭제
    """
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


@login_required(login_url='common:login')
def full_remove(request, product_id):
    """
    cart 전체 삭제
    """
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load product_filter %}
{% load humanize %}
{% block content %}
    {% load static %}
    {#<div class="row mt-5">#}
    {#    <div class="col-12" style="text-align: center">#}
    {#        <h3> 장바구니 </h3>#}
    {#    </div>#}
    {#</div>#}
    {% if not cart_items %}
        <div class="container">
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">장바구니가 비어있습니다.</h1><br>
                <p class="text-center">
                    <a href="{% url 'product:index' %}">돌아가기</a>
                </p>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">장바구니</h1><br>
            </div>
        </div>
{#        <div class="col-10">#}
        <div class="row-1">
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_customer_table">
                        <thead class="my_custom_thread">
                        <tr>
                            <th colspan="5">
                                상품
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <div><p>{{ cart_item.product.image|safe }}</p></div>
                                </td>
                                <td class="text-left">
                                    {{ cart_item.product.name }}
                                    <br>
                                    번호: {{ cart_item.product.id }}
                                    <br>
                                    <span class="num">가격: {{ cart_item.product.price|intcomma }}원</span>
                                    <br>
                                    <span class="num">수량: {{ cart_item.quantity }} X {{ cart_item.product.price|intcomma }} 원</span>
                                </td>
                                <td>
                                    {{ cart_item.sub_total|intcomma }}원
                                </td>
                                {% if cart_item.quantity <= cart_item.product.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                                            <i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i
                                                class="fas fa-minus-circle custom_icon"></i></a>
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i
                                                class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}"
                                                 class="custom_a"><i
                                            class="fas fa-minus-circle custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i
                                                class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_customer_table">
                        <thead class="my_custom_thread">
                        <tr>
                            <th>
                                총계
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                상품 개수와 당신이 지불하려는 총 금액을 확인하고 결제하세요
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                총 금액 : <strong>{{ total|intcomma }}원</strong>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <form action="" method="POST">
                            <script
                                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="{{ data_key }}"
                                    data-image="{% static 'img/logo.JPG' %}"
                                    data-name="Best SmartPhone Shop"
                                    data-description={{ description }}
                                    data-amount="{{ stripe_total }}"
                                    data-label="결제하기"
                                    data-currency="krw"
                                    data-shpping-address="true"
                                    data-billing-address="true"
                                    data-zip-code="true">
                            </script>
                        </form>
                        <a href="{% url 'product:index' %}" class="btn btn-secondary btn-block my_custom_button">쇼핑
                            계속하기</a>
                    </div>
                </div>
            </div>
        </div>
        <br>
    {% endif %}
{% endblock %}

cart/templates/cart/order_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <body onload="showClock()">
    <div class="mt-5 pt-5 row justify-content-center">
        <h2 class="text-center my-5 col-12">결제가 완료되었습니다!</h2>
        <div class="col-4 p-5 bg-light">
            <h3 class="text-center my-5">주문자 정보</h3>
            <div>
                <div class="my-3 row">
                    <div class="h5 col-6">유저</div>
                    <div class="h6 col-6 text-right">{{ user.username }}</div>
                </div>
                <div class="my-3 row">
                    {% for cart_item in cart_items %}
                        <div class="h5 col-6">상품</div>
                        <div class="h6 col-6 text-right">{{ cart_item.product.name }} X {{ cart_item.quantity }}</div>
                    {% endfor %}
                </div>
                <div class="my-3 row">
                    <div class="h5 col-6">총 결제금액</div>
                    <div class="h6 col-6 text-right">{{ stripe_total|intcomma }}원</div>
                </div>
            </div>
            <div class="mt-5 pt-3 text-center">
                <a href="{% url 'product:index' %}" class="btn btn-warning">메인으로 돌아가기</a>
            </div>

        </div>

    </div>
    </body>

{% endblock %}

cart/templates/cart/pay.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
{#    결제 완료 창 #}
    <div class="mt-5 pt-5 row justify-content-center">
        <h2 class="text-center my-5 col-12">결제가 완료되었습니다!</h2>
        <div class="col-4 p-5 bg-light">
            <h3 class="text-center my-5">주문자 정보</h3>
            <div>
                <div class="my-3 row">
                    <div class="h5 col-6">유저</div>
                    <div class="h6 col-6 text-right">{{ user.username }}</div>
                </div>
                <div class="my-3 row">
                    {% for cart_item in cart_items %}
                        <div class="h5 col-6">상품</div>
                        <div class="h6 col-6 text-right">{{ cart_item.product.name }} X {{ cart_item.quantity }}</div>
                    {% endfor %}
                </div>
                <div class="my-3 row">
                    <div class="h5 col-6">총 결제금액</div>
                    <div class="h6 col-6 text-right">{{ stripe_total|intcomma }}원</div>
                </div>
            </div>
            <div class="mt-5 pt-3 text-center">
                <a href="{% url 'product:index' %}" class="btn btn-warning">메인으로 돌아가기</a>
            </div>
        </div>
    </div>
{% endblock %}