cart/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

import product.views
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>/', views.detail, name='detail'),
    # path('/register', views.register, name='register'),
    # path('create/', views.ProductCreate.as_view(), name='register'),
    path('create/', views.product_create, name='register'),
    path('modify/<int:product_id>/', views.product_modify, name='modify'),
    path('delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('search', views.search, name='search'),

]

product/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    # image를 텍스트 필드로 한 이유는 좀더 아름답게 만들기 위해서 (summernote 이용)
    image = models.TextField()
    price = models.IntegerField()
    stock = models.IntegerField()
    # image = models.ImageField(upload_to="product", blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "product"
        verbose_name = "상품"
        verbose_name_plural = "상품"

product/forms.py
from django import forms

from product.models import Product


# class RegisterForm(forms.Form):
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'image', 'stock']
        labels = {'name': '상품명', 'price': '상품 가격', 'description': '상품 설명',
                  'image': '상품 이미지', 'stock': '재고', }

    # name = forms.CharField(
    #     error_messages={
    #         'required': '상품명을 입력해주세요.'
    #     }, label="상품명", max_length=64)
    #
    # price = forms.IntegerField(
    #     error_messages={
    #         'required': "상품 가격을 입력해주세요."
    #     }, label="상품 가격",
    # )
    # description = forms.CharField(
    #     error_messages={
    #         'required': "상품 설명을 입력해주세요."
    #     }, label="상품 설명"
    # )
    # image = forms.CharField(
    #     error_messages={
    #         'required': "상품 이미지를 넣어주세요."
    #     }, label="상품 이미지"
    # )
    # stock = forms.IntegerField(
    #     error_messages={
    #         'required': "재고를 입력해주세요."
    #     }, label="재고"
    # )

    # validate
    # def clean(self):
    #     cleaned_data = super().clean()
    #     name = cleaned_data.get('name')
    #     price = cleaned_data.get('price')
    #     description = cleaned_data.get('description')
    #     image = cleaned_data.get('image')
    #     stock = cleaned_data.get('stock')
    #
    #     if name and price and description and image and stock:
    #         product = Product(
    #             name=name,
    #             price=price,
    #             description=description,
    #             image=image,
    #             stock=stock
    #         )
    #         product.save()

product/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import FormView

# from product.forms import RegisterForm, ProductForm
from product.forms import ProductForm
from product.models import Product


def index(request):
    """
    product 목록 출력
    """
    page = request.GET.get('page', '1')
    product_list = Product.objects.order_by('-created')
    paginator = Paginator(product_list, 6)
    page_obj = paginator.get_page(page)
    context = {'product_list': page_obj}
    # context = {'product_list': product_list}

    return render(request, 'product/product_list.html', context)


def detail(request, product_id):
    """
    product 내용 출력
    """
    # product = Product.objects.get(id=product_id)
    # Product.objects.get(id=product_id)
    product = get_object_or_404(Product, pk=product_id)
    context = {'product': product}

    return render(request, 'product/product_detail.html', context)


# class ProductCreate(FormView):
#     template_name = 'product/product_register.html'
#     form_class = RegisterForm
#     success_url = '/product/'


# class ProductModify(FormView):
#     template_name = 'product/product_register.html'
#     form_class = RegisterForm
#     success_url = '/product/'


@login_required(login_url='common:login')
def product_create(request):
    """
    product 등록
    """
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('product:index')
    else:
        form = ProductForm()
    context = {'form': form}

    return render(request, 'product/product_register.html', context)


@login_required(login_url='common:login')
def product_modify(request, product_id):
    """
    product 수정
    """
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('product:detail', product_id=product_id)
    else:
        form = ProductForm(instance=product)
    context = {'form': form}
    return render(request, 'product/product_register.html', context)


@login_required(login_url='common:login')
def product_delete(request, product_id):
    """
    product 삭제
    """
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return redirect('product:index')


def search(request):
    """
    product 검색
    """
    products = None
    keyword = None

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        products = Product.objects.all().filter(name__contains=keyword)

    context = {
        'products': products, 'keyword': keyword,
    }

    return render(request, 'product/search.html', context)

product/templates/product/product_detail.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    {% load humanize %}

    <div class="container">
        <br>
        <h2><p class="text-center">상품</p></h2>
        <hr>


        <div class="card">
            <div class="row">
                <aside class="col-sm-3 border-right">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            {#  <div> <a href="#"><img src="/static/media/product/Iphone_12_pro.jpg" alt="iphone12pro"></a></div>#}
                            {#  <div><img src="/static/media/product/Iphone_12_pro.jpg" alt="iphone12pro" width="250" height="300"/></div>#}
                            {#                            summernote 적용전 쓰던거#}
                            {#                            <div><img src="/static/{{ product.image.path }}" width="250" height="300" alt="{{ product.name }}"/></div>#}
                            <div><p>{{ product.image|safe }}</p></div>
                        </div>
                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <aside class="col-sm-7">
                    <article class="card-body p-5">
                        <dl class="item-property">
                            <dt><h3>상품 이름</h3></dt>
                        </dl>
                        <h3 class="title mb-3">{{ product.name }}</h3>
                        <dl class="item-property">
                            <dt>가격</dt>
                        </dl>
                        <p class="price-detail-wrap">
	                        <span class="price h3 text-warning">
	                        	<span class="num">{{ product.price|intcomma }}</span><span class="currency"> 원</span>
	                        </span>
                        </p>
                        <dl class="item-property">
                            <dt>스펙</dt>
                            <dd><p>{{ product.description }}</p></dd>
                        </dl>
                        {#<dl class="param param-feature">#}
                        {#  <dt>모델 번호</dt>#}
                        {#  <dd>{{ product.id }}</dd>#}

                        <dl class="param param-feature">
                            <dt>재고</dt>
                            <dd>{{ product.stock }}</dd>
                        </dl>
                        <dl class="param param-feature">
                            <dt>배송</dt>
                            <dd>코로나 시국이라 택배배송만</dd>
                        </dl>
                        {% if user.is_authenticated and not user.is_staff %}
                            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-lg btn-primary text-uppercase">장바구니</a>
                            <a href="{% url 'product:index' %}"
                               class="btn btn-lg btn-outline-primary text-uppercase">돌아가기</a>
                        {% elif user.is_authenticated and user.is_staff %}
                            <a href="{% url 'product:modify' product.id %}" class="btn btn-lg btn-primary text-uppercase">수정</a>
{#                            <a href="#" class="btn btn-lg btn-primary text-uppercase">수정</a>#}
                            <a href="{% url 'product:product_delete' product.id %}" class="delete btn btn-lg btn-primary text-uppercase">삭제</a>
                            <a href="{% url 'product:index' %}"
                               class="btn btn-lg btn-outline-primary text-uppercase">돌아가기</a>
                        {% endif %}
                    </article>
                </aside>
            </div>
        </div>


    </div>



    <br><br>
    <article class="bg-secondary mb-0">
        <div class="card-body text-center">
            <br><br>
            <h4 class="text-white">Best SmartPhone Shop<br></h4>
            <p class="h5 text-white">@CopyRight by AWOS</p>
        </div>
    </article>
{% endblock %}

product/templates/product/product_list.html
{#{% extends 'base.html' %}#}
{#{% load product_filter %}#}
{#{% load humanize %}#}
{#{% block content %}#}
{#{% load static %}#}
{#<div class="row mt-5">#}
{#    <div class="col-12" style="text-align: center">#}
{#        <h3> 상품목록 </h3>#}
{#    </div>#}
{#</div>#}
{#<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">#}
{#<div class="container my-3">#}
{#    <table class="table">#}
{#        <thead>#}
{#        <tr class="thead-dark">#}
{#            <th class="text-center">번호</th>#}
{#            <th style="width:50%">상품명</th>#}
{#            <th class="text-center">가격</th>#}
{#            <th class="text-center">재고</th>#}
{#            <th class="text-center">등록일시</th>#}
{#        </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#        {% if product_list %}#}
{#        {% for product in product_list %}#}
{#        <tr class="text-center">#}
{#            <td>{{ product_list.paginator.count|sub2:product_list.start_index|sub2:forloop.counter0|add:1 }}</td>#}
{#            <td class="text-left">#}
{#                <a href="{% url 'product:detail' product.id %}">{{ product.name }}</a>#}
{#            </td>#}
{#            <td>{{ product.price|intcomma }}원</td>#}
{#            <td>{{ product.stock }}</td>#}
{#            <td>{{ product.created | date:'Y-m-d H:i'}}</td>#}
{#        </tr>#}
{#        {% endfor %}#}
{#        {% else %}#}
{#        <tr>#}
{#            <td colspan="3">상품이 없습니다.</td>#}
{#        </tr>#}
{#        {% endif %}#}
{#        </tbody>#}
{#    </table>#}
{#    <!-- 페이징처리 시작 -->#}
{#    <ul class="pagination justify-content-center">#}
{#        <!-- 이전페이지 -->#}
{#        {% if question_list.has_previous %}#}
{#        <li class="page-item">#}
{#            <a class="page-link" href="?page={{ product_list.previous_page_number }}">이전</a>#}
{#        </li>#}
{#        {% else %}#}
{#        <li class="page-item disabled">#}
{#            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>#}
{#        </li>#}
{#        {% endif %}#}
{#        <!-- 페이지리스트 -->#}
{#        {% for page_number in product_list.paginator.page_range %}#}
{#        {% if page_number >= product_list.number|add:-5 and page_number <= product_list.number|add:5 %}#}
{#            {% if page_number == product_list.number %}#}
{#            <li class="page-item active" aria-current="page">#}
{#                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>#}
{#            </li>#}
{#            {% else %}#}
{#            <li class="page-item">#}
{#                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>#}
{#            </li>#}
{#            {% endif %}#}
{#        {% endif %}#}
{#        {% endfor %}#}
{#        <!-- 다음페이지 -->#}
{#        {% if product_list.has_next %}#}
{#        <li class="page-item">#}
{#            <a class="page-link" href="?page={{ product_list.next_page_number }}">다음</a>#}
{#        </li>#}
{#        {% else %}#}
{#        <li class="page-item disabled">#}
{#            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>#}
{#        </li>#}
{#        {% endif %}#}
{#    </ul>#}
{#    <!-- 페이징처리 끝 -->#}
{#    <a href="{% url 'product:register' %}" class="btn btn-primary">상품 등록하기</a>#}
{##}
{#    <a {% if not user.is_authenticated %}disabled{% endif %} class="btn btn-primary" style="float:right">상품 등록하기</a>#}
{#    <a {% if not user.is_authenticated %}disabled{% endif %} class="btn btn-primary" style="float:right">상품 등록하기</a>#}
{#    <a {% if not user.is_authenticated %}disabled{% endif %} class="btn btn-primary" style="float:left">상품 구매하기</a>#}
{##}
{#    <a class="btn btn-primary btn-lg {% if not user.is_authenticated %}disabled{% endif %}" style="float:right">상품 등록하기</a>#}
    {# 일단은 로그인하지 않은 사용자들에게는 구매, 등록 버튼이 보이지 않음 #}
{##}
{#    {% if user.is_authenticated and user.is_staff %}#}
{#        <a class="btn btn-primary" href="{% url 'product:register' %}" style="float:right">상품 등록하기</a>#}
{#        <a class="btn btn-primary" href="#" style="float:left">상품 구매하기</a>#}
{#    {% endif %}#}
{##}
{##}
{##}
{##}
{##}
{#</div>#}
{#{% endblock %}#}

{% extends 'base.html' %}
{% load product_filter %}
{% load humanize %}
{% block content %}
{% load static %}
<div class="row mt-5">
    <div class="col-12" style="text-align: center">
        <h3> 상품목록 </h3>
    </div>
</div>
{#<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">#}
    <div class="container">
        <div class="row mx-auto">
            {% if product_list %}
        {% for product in product_list %}
{#            <p{{ product_list.paginator.count|sub2:product_list.start_index|sub2:forloop.counter0|add:1 }}></p>#}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                    <div class="card text-center" style="min-width: 18rem;">
                        <a href="{{ product.id }}"><p class="card-img-top my_image">{{ product.image|safe }}</p>
                        </a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price|intcomma }}원</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <div class="row mx-auto">
                    <p>상품이 없습니다.</p>
                </div>
            {% endif %}
        </div>
    </div>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if product_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ product_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in product_list.paginator.page_range %}
        {% if page_number >= product_list.number|add:-5 and page_number <= product_list.number|add:5 %}
            {% if page_number == product_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if product_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ product_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    {% if user.is_authenticated and user.is_staff %}
        <a class="btn btn-primary" href="{% url 'product:register' %}" style="float:right">상품 등록하기</a>
    {% endif %}
</div>
{% endblock %}

product/templates/product/product_register.html
{% extends "base.html" %}
{#{% load static %}#}
{% block header %}
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
{% endblock %}
{% block content %}
    <div class="row mt-3">
        <div class="col-12 text-center">
            <h1>상품 등록</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            {{ error }}
        </div>
    </div>
    <div class="container my-3">
        <div class="row mt-5">
            <div class="col-12">
                <form method="POST" action=".">
                    {% csrf_token %}
                    <!-- 커스터마이징 -->
                    <!-- form을 반복문에 넣으면 각 필드별로 나온다 -->
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {% if field.name == 'description' %}
                                <textarea class="form-control" name="{{ field.name }}"
                                          id="{{ field.id_for_label }}">{{ field.value|default_if_none:'' }}</textarea>
                            {% else %}
                                {% if field.name == 'image' %}
                                    <textarea class="form-control" name="{{ field.name }}"
                                              id="{{ field.id_for_label }}">{{ field.value|default_if_none:'' }}</textarea>
                                    <script>
                                        $(document).ready(function () {
                                            $('#id_image').summernote({
                                                {#$('summernote').summernote({#}
                                                height: 150
                                            });
                                        });
                                    </script>
                                {% else %}
                                    <input type="{{ field.field.widget.input_type }}" class="form-control"
                                           id="{{ field.id_for_label }}"
                                           placeholder="{{ field.label }}" name="{{ field.name }}"
                                           value="{{ field.value|default_if_none:'' }}"/>
                                {% endif %}

                            {% endif %}
                        </div>
                        {% if field.errors %}
                            <span style="color: red">{{ field.errors }}</span>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">생성</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/search.html
{% extends 'base.html' %}
{% block content %}
    {% load humanize %}
    <div>
        <p class="text-center product_search_text">검색 결과 : <b>"{{ keyword }}"</b></p>
    </div>
    <div class="container">
        <div class="row mx-auto">
            {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                    <div class="card text-center" style="min-width: 18rem;">
                        <a href="{{ product.id }}"><p class="card-img-top my_image">{{ product.image|safe }}</p>
                        </a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price|intcomma }}원</p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="row mx-auto">
                    <p class="text-center product_search_text">검색 결과 없음</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}