cart/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

import product.views
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:product_id>/', views.detail, name='detail'),
    # path('/register', views.register, name='register'),
    # path('create/', views.ProductCreate.as_view(), name='register'),
    path('create/', views.product_create, name='register'),
    path('modify/<int:product_id>/', views.product_modify, name='modify'),
    path('delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('search', views.search, name='search'),

]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {'subject': '제목', 'content': '내용', }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .forms import QuestionForm, AnswerForm
from .models import Question, Answer


def index(request):
    page = request.GET.get('page', '1')
    # DB 기본 정렬 : ASC. -를 붙이면 역순으로 정렬.
    question_list = Question.objects.order_by('-create_date')
    # 1page당 10개의 게시물을 가져옴.
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    #context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user    # 추가한 속성 author 적용
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    # question.answer_set.create(content=request.POST.get('cont'), create_date=timezone.now())

    # 다른 방법
    # answer = Answer(question=question, content=request.POST.get('cont'), create_date=timezone.now())
    # answer.save()
    # ---------------------------------- [edit] ---------------------------------- #
    # return redirect('pybo:detail', question_id=question.id)
    # ---------------------------------------------------------------------------- #


@login_required(login_url='common:login')
def question_create(request):
    # form = QuestionForm()
    # return render(request, 'pybo/question_form.html', {'form': form})
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.author = request.user  # 추가한 속성 author 적용
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}

    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 업습니다.')
        return redirect('pybo:detail', question_id=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now() # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/templates/base.html
{#  중복된 불필요한 파일들을 제거해줌  #}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">
{#    <link rel="stylesheet", type="text/css", href="{% static 'bootstrap.min.css' %}">#}
{#    <link rel="stylesheet", type="text/css", href="{% static 'style.css' %}">#}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
{#    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome.min.css' %}">#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'all.min.css' %}">#}
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
  />
    <title>Title</title>
    {% block header %}
    {% endblock %}
</head>
<body>
{## include 해당 위치에 다른 문서의 내용을 삽입시킴#}
{% include "navbar.html" %}
{% block content %}
{% endblock %}
{#<br><br>#}
{#    <article class="bg-secondary mb-0">#}
{#        <div class="card-body text-center">#}
{#            <br><br>#}
{#            <h4 class="text-white">Best SmartPhone Shop<br></h4>#}
{#            <p class="h5 text-white">@CopyRight by AWOS</p>#}
{#        </div>#}
{#    </article>#}
{#<script src="{% static 'jquery-3.6.0.min.js' %}"></script>#}
{#<script src="{% static 'bootstrap.min.js' %}"></script>#}
{#<script src="{% static 'popper.min.js' %}"></script>#}
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

pybo/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

pybo/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'product:index' %}">Best<br>SmartPhone</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {#                <a class="nav-link" href="#">로그인</a>#}
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'product:index' %}">상품목록</a>
            </li>
            {#        로그인한 유저가 아니거나 관리자가 아니면 장바구니와 장바구니에 수량이 뜸#}
            {% if user.is_authenticated and not user.is_staff %}
                {% if item_count > 0 %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">장바구니({{ item_count }})</a>
                    </li>
                {% else %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">장바구니</a>
                    </li>
                {% endif %}
            {% endif %}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'pybo:index' %}">고객센터</a>
            </li>
        </ul>
    </div>
</nav>
<nav class="navbar navbar-expand-sm bg-light navbar-dark justify-content-end">
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <form class="form-inline my-2 my-lg-0" action="{% url 'product:search' %}" method="get">
                    {% csrf_token %}
                    <label>
                        <input class="form-control mr-sm-2" type="search" placeholder="상품 검색" name="keyword">
                    </label>
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </li>
        </ul>
    </div>
</nav>